language: c
compiler:
  - gcc
  - clang
env:
  - CONFIGURE_ARGS=""
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y --no-install-recommends libpam0g-dev asciidoc gengetopt docbook-xml xsltproc libxml2-utils $EXTRA
env:
  - EXTRA="libjson0-dev check help2man libudev-dev libusb-1.0-0-dev"
script:
  - ./build-aux/travis
